name: ci

on: [push, pull_request]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      -
        id: get-version
        uses: battila7/get-version-action@v2
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: crallen
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: crallen/gl-inet-sdk:latest